spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: "com.personal.account.serializer.MessageSerializer"

#can use jsonserializer also like below:-
#org.springframework.kafka.support.serializer.JsonSerializer
